package dependency

object Versions {
    const val LincollincolAmplituda = "2.2.2"
    const val KtorClientAndroid = "2.3.4"
    const val HlitComposeNavigation = "1.0.0"
    const val NavigationCompose = "2.6.0"
    const val Mosi = "1.14.0"
    const val Retrofit = "2.9.0"
    const val AndroidXCoreKtx = "1.9.0"
    const val LifecycleRuntimeKtx = "2.6.1"
    const val ActivityCompose = "1.7.0"
    const val ComposeBom = "2023.03.00"
    const val HlitAndroid = "2.44"
    const val HiltAndroidCompiler = "2.44"
    const val KoltinCompose = "2.4.0"
    const val HiltComposeNavigation = "1.0.0"
    const val AallamOpenAi = "3.4.1"
    const val ComposeConstraintLayout = "1.0.1"
    const val ComposeAudiowaveForm = "1.1.1"
    const val AndroidXStartup = "1.1.1"
    const val AccompanistPermission = "0.30.1"
    const val Room = "2.5.2"
    const val Hlit = "2.44"
    const val TensorflowLite = "0.4.4"
    const val Jna = "5.13.0"
    const val VoskAndroid = "0.3.47"
    const val Jtokkit = "1.0.0"
}